
@urlComercios = http://localhost:3000/comercios/
@urlUsuarios = http://localhost:3000/usuarios/
@urlAutenticacion = http://localhost:3000/autenticacion/

POST {{urlAutenticacion}}
Content-Type: application/json

{
    "usuario":"carolina",
    "clave":"1234"
}
###
//Comercios
GET {{urlComercios}}
### 
POST {{urlComercios}} 
Content-Type: application/json

{
    "latitud":"38.8951",
    "longitud":"-77.0364",
    "nombre":"La esquina del sabor",
    "nombrePropietario":"Antony Duarte",
    "telefono":"70079032",
    "categoria":"Comida Mexicana",
    "descripcion":"Descripcion random",
    "direccion":"Chalatenango"
}
###

GET {{urlComercios}}61494f97f714b8c2f6a429eb
###

PUT {{urlComercios}}614951a39dc835a135f61b63 
Content-Type: application/json

{
"nombre":"Comercio 01 modificado", "direccion":"Nueva Concepcion"
}
###
DELETE {{urlComercios}}61494f97f714b8c2f6a429eb

//show dbs //use empredeapp //show collections //db.comercios.find()
###

//USUARIOS
GET {{urlUsuarios}}
### 
POST {{urlUsuarios}}
Content-Type: application/json

{
    "nombre":"Carolina Serrano", 
    "usuario":"carolina",
    "email":"serrano@gmail.com", 
    "usuario":"carolina", 
    "password":"1234",
    "activo":true
}
###

GET {{urlUsuarios}}614951e19dc835a135f61b68
###

PUT {{urlUsuarios}}614951e19dc835a135f61b68 
Content-Type: application/json

{

    "nombre":"Carolina Serrano Luna", 
    "email":"serrano@gmail.com", 
    "usuario":"carolina", 
    "password":"1234"
}
###
DELETE {{urlUsuarios}}614951e19dc835a135f61b68